### PR TITLE
Link to Sonus from README

### PR DESCRIPTION
**Pull request by evancohen**
x-ref: #10

Tried to stick to the same general tone of your existing README. Happy to make any revisions you see fit.

### CODE REVIEW

**Comment by hackergrrl** [comment]
Thanks, Evan. I haven't managed to get sonus working yet, but I'll merge this and report back once I do.

**Comment by evancohen** [comment]
Don't be afraid to holler if you have any issues :)

**Comment by evancohen** [comment]
Hey @noffle any chance of merging this still? I've got Sonus working in Electron now:
https://github.com/evancohen/sonus-electron-boilerplate

**Comment by evancohen** [comment]
Monthly reminder :)

**Comment by hackergrrl** [comment]
@evancohen I've taken _forever_ to merge this. Thank you Evan! :tada:

**Pull request merged**
